package com.squirrelhill.ibesper.ibmodel;

public class NegativeTimeException extends Exception {
	/**
	 * autogenerated
	 */
	private static final long serialVersionUID = 1062970205907034683L;

	public NegativeTimeException(String message) {
		super(message);
	}
	
	public NegativeTimeException(String message, Throwable cause) {
		super(message, cause);
	}
}
